#!/bin/sh
# Generates compose/appsettings.json on first run from the shipped
# example, substituting per-deployment values: the public hostname
# from compose/.env and a freshly-generated XorKey.
#
# Idempotent: if appsettings.json already exists, exits 0 without
# touching it. Operators who want to re-render must delete the file
# first.
#
# Called automatically by `make platform-up` as a prerequisite. Can
# also be run on its own (`make init-config`).

set -eu

cd "$(dirname "$0")/../compose"

if [ -f appsettings.json ]; then
    echo "compose/appsettings.json already exists — leaving it alone."
    echo "  (delete it first if you want to regenerate from the example)"
    exit 0
fi

if [ ! -f appsettings.example.json ]; then
    echo "ERROR: compose/appsettings.example.json missing — can't bootstrap." >&2
    exit 1
fi

# Load .env so PUBLIC_ENTRY / WORKSPACE are available. The file uses
# shell-style KEY=VALUE so `. ./.env` works.
if [ ! -f .env ]; then
    echo "ERROR: compose/.env missing — copy from the repo or fill in values." >&2
    exit 1
fi
# shellcheck disable=SC1091
. ./.env

# Hard-fail if PUBLIC_ENTRY is still the placeholder.
PUBLIC_ENTRY="${PUBLIC_ENTRY:-}"
case "$PUBLIC_ENTRY" in
    ""|*"{{"*"}}"*|"<"*">"*)
        echo "ERROR: PUBLIC_ENTRY in compose/.env is unset or still the placeholder." >&2
        echo "  Set it to your platform's public hostname (e.g. ctf.example.com)." >&2
        exit 1
        ;;
esac

# WORKSPACE is just a docker-compose project name + traefik route
# suffix — auto-pick something slug-safe if the operator left the
# placeholder. Rotating it later means losing the existing
# docker-compose project's volume bindings, so we persist the chosen
# value back to .env (same caveat as XorKey).
WORKSPACE="${WORKSPACE:-}"
case "$WORKSPACE" in
    ""|*"{{"*"}}"*|"<"*">"*)
        if command -v openssl >/dev/null 2>&1; then
            WS_SUFFIX="$(openssl rand -hex 4)"
        elif [ -r /dev/urandom ]; then
            WS_SUFFIX="$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
        else
            WS_SUFFIX="default"
        fi
        WORKSPACE="gzctf-$WS_SUFFIX"
        # Overwrite the placeholder line if present, otherwise append.
        if grep -qE '^WORKSPACE=' .env; then
            # Portable in-place: write to temp + replace
            sed 's|^WORKSPACE=.*|WORKSPACE="'"$WORKSPACE"'"|' .env > .env.tmp \
                && mv .env.tmp .env
        else
            printf '\nWORKSPACE="%s"\n' "$WORKSPACE" >> .env
        fi
        echo "Auto-picked WORKSPACE=$WORKSPACE (persisted to .env)"
        ;;
esac

# Generate a strong XorKey (used to obfuscate registry passwords + repo
# binding tokens at rest). 64 hex chars = 256 bits of entropy.
if [ -n "${XOR_KEY:-}" ]; then
    XK="$XOR_KEY"
else
    if command -v openssl >/dev/null 2>&1; then
        XK="$(openssl rand -hex 32)"
    elif [ -r /dev/urandom ]; then
        XK="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    else
        echo "ERROR: openssl missing and /dev/urandom unreadable — can't generate XorKey." >&2
        exit 1
    fi
    # Persist so re-runs land on the same key (important: rotating XorKey
    # breaks every encrypted token + registry password already in the DB).
    if [ -w .env ]; then
        printf '\n# Auto-generated by scripts/init-config.sh on %s\nXOR_KEY=%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$XK" >> .env
    fi
fi

# Render with literal-string sed substitutions. The example uses
# `{{.PublicEntry}}` and `{{.XorKey}}` (gzcli placeholder style).
# Escape any sed-special chars in the values.
escape_sed() {
    printf '%s' "$1" | sed 's|[\\&|]|\\&|g'
}
PUBLIC_ENTRY_ESC=$(escape_sed "$PUBLIC_ENTRY")
XK_ESC=$(escape_sed "$XK")

sed \
    -e "s|{{\\.PublicEntry}}|$PUBLIC_ENTRY_ESC|g" \
    -e "s|{{\\.XorKey}}|$XK_ESC|g" \
    appsettings.example.json > appsettings.json

chmod 600 appsettings.json

echo "Generated compose/appsettings.json"
echo "  PUBLIC_ENTRY = $PUBLIC_ENTRY"
echo "  WORKSPACE    = $WORKSPACE"
echo "  XorKey       = (auto-generated, 256 bits)"
echo "  Edit the file to set admin password, SMTP creds, captcha, etc."
echo "  It's chmod 600 + in .gitignore — never commit it."
